import type { Build, Hero, MapGuide, Matchup, Race, Unit } from "./types";

export const races: Race[] = [
  {
    slug: "human",
    name: "Human",
    badge: "Alliance Discipline",
    identity: "Flexible macro with strong expansion timings and layered spell support.",
    description:
      "Human wins by stabilizing early creep routes, protecting economy, and turning precise caster support into decisive tempo swings.",
    strengths: ["Militia-assisted map control", "Safe expansions", "Strong late-game spell utility"],
    signatureHeroes: ["Archmage", "Mountain King", "Paladin"],
    ladderFocus: "Secure creeping routes, preserve peasants, and expand on favorable map flow.",
  },
  {
    slug: "orc",
    name: "Orc",
    badge: "Iron Horde Tempo",
    identity: "Explosive skirmishing backed by durable units and high-value hero pressure.",
    description:
      "Orc thrives when it dictates the pace with hero focus fire, clean itemization, and a transition that lands before the opponent stabilizes.",
    strengths: ["Early hero pressure", "Efficient tier-two timing", "Excellent focus fire"],
    signatureHeroes: ["Blademaster", "Far Seer", "Shadow Hunter"],
    ladderFocus: "Force reactions, scout constantly, and punish greedy tech or expansion patterns.",
  },
  {
    slug: "night-elf",
    name: "Night Elf",
    badge: "Moonwell Control",
    identity: "Mobility, map pressure, and high-upkeep avoidance through tempo-sensitive play.",
    description:
      "Night Elf leverages map presence, healing efficiency, and adaptable hero compositions to stretch opponents across multiple fronts.",
    strengths: ["Map mobility", "Sustain through Moon Wells", "Tactical tech switches"],
    signatureHeroes: ["Demon Hunter", "Keeper of the Grove", "Warden"],
    ladderFocus: "Creep efficiently, deny safe expansions, and convert mobility into resource advantages.",
  },
  {
    slug: "undead",
    name: "Undead",
    badge: "Necropolis Pressure",
    identity: "Precise creeping, punishing timing attacks, and elite ranged damage backed by statues.",
    description:
      "Undead rewards players who protect fragile unit counts early, hit core timing windows, and convert superior hero leveling into map control.",
    strengths: ["Reliable nuke damage", "Strong timing pushes", "Efficient sustain with statues"],
    signatureHeroes: ["Death Knight", "Lich", "Crypt Lord"],
    ladderFocus: "Keep experience flowing, protect fiend numbers, and decide when to all-in versus expand.",
  },
  {
    slug: "neutral",
    name: "Neutral",
    badge: "Mercenary Arsenal",
    identity: "Shop, mercenary, and support options that any army can leverage for tempo, scouting, or utility.",
    description:
      "Neutral units fill tactical gaps with dispel, healing, anti-air support, transport, and surprise timing options from taverns, merc camps, and goblin labs.",
    strengths: ["Flexible utility", "Cross-race tactical value", "Powerful niche timing tools"],
    signatureHeroes: ["N/A"],
    ladderFocus: "Use neutral pickups to patch weaknesses, spike timings, and punish opponents who scout too late.",
  },
];

export const heroes: Hero[] = [
  {
    slug: "archmage",
    name: "Archmage",
    raceName: "Human",
    description: "A macro enabler whose brilliance aura and summons unlock Human's most stable openings.",
    primaryAttribute: "Intelligence",
    role: "Tempo support",
    highlights: ["Smooth early creeping", "Improves caster mana economy", "Reliable expansion partner"],
  },
  {
    slug: "mountain-king",
    name: "Mountain King",
    raceName: "Human",
    description: "A control-heavy second hero that turns focus fire windows into guaranteed unit kills.",
    primaryAttribute: "Strength",
    role: "Single-target lockdown",
    highlights: ["Storm Bolt pressure", "Frontline durability", "Pairs well with rifles and casters"],
  },
  {
    slug: "paladin",
    name: "Paladin",
    raceName: "Human",
    description: "A defensive Human hero that adds healing, sustain, and late-game frontline value to prolonged fights.",
    primaryAttribute: "Strength",
    role: "Sustain support",
    highlights: ["Holy Light saves", "Excellent versus Undead", "Scales in long macro games"],
  },
  {
    slug: "blood-mage",
    name: "Blood Mage",
    raceName: "Human",
    description: "A utility spellcaster hero built around mana control, area denial, and explosive spell combos.",
    primaryAttribute: "Intelligence",
    role: "Spell utility",
    highlights: ["Mana Siphon control", "Flame Strike siege threat", "Strong in caster-heavy compositions"],
  },
  {
    slug: "blademaster",
    name: "Blademaster",
    raceName: "Orc",
    description: "The classic Orc carry hero built around scouting, item scaling, and punishing exposed targets.",
    primaryAttribute: "Agility",
    role: "Harass carry",
    highlights: ["Exceptional scouting", "Item-dependent burst", "Forces defensive reactions"],
  },
  {
    slug: "shadow-hunter",
    name: "Shadow Hunter",
    raceName: "Orc",
    description: "The stabilizer behind Orc's midgame with healing wave sustain and hex control.",
    primaryAttribute: "Intelligence",
    role: "Backline support",
    highlights: ["Healing Wave sustain", "Hex for hero catches", "Improves grunts and raiders longevity"],
  },
  {
    slug: "far-seer",
    name: "Far Seer",
    raceName: "Orc",
    description: "A scouting and tempo hero that creates early pressure with summons, chain lightning, and map presence.",
    primaryAttribute: "Intelligence",
    role: "Tempo pressure",
    highlights: ["Excellent scouting", "Strong tier-one pressure", "Flexible creeping and harassment routes"],
  },
  {
    slug: "tauren-chieftain",
    name: "Tauren Chieftain",
    raceName: "Orc",
    description: "A bruiser control hero that gives Orc armies durable frontline value and punishing area stun potential.",
    primaryAttribute: "Strength",
    role: "Frontline disruptor",
    highlights: ["War Stomp control", "High durability", "Excellent in extended melee fights"],
  },
  {
    slug: "demon-hunter",
    name: "Demon Hunter",
    raceName: "Night Elf",
    description: "A mana denial specialist that keeps enemy heroes honest while anchoring mobile skirmishes.",
    primaryAttribute: "Agility",
    role: "Anti-caster duelist",
    highlights: ["Mana Burn pressure", "High mobility", "Excellent frontline scaling"],
  },
  {
    slug: "keeper-of-the-grove",
    name: "Keeper of the Grove",
    raceName: "Night Elf",
    description: "A map-control hero that punishes greed and turns entangle into repeated economic damage.",
    primaryAttribute: "Intelligence",
    role: "Map pressure",
    highlights: ["Entangle pickoffs", "Treant creeping", "Strong versus exposed expansions"],
  },
  {
    slug: "priestess-of-the-moon",
    name: "Priestess of the Moon",
    raceName: "Night Elf",
    description: "A ranged aura hero that supports tempo pushes, hunts pressure, and coordinated archer-based openings.",
    primaryAttribute: "Agility",
    role: "Aura support",
    highlights: ["Trueshot Aura scaling", "Solid ranged pressure", "Useful for tempo-oriented openers"],
  },
  {
    slug: "warden",
    name: "Warden",
    raceName: "Night Elf",
    description: "A burst-damage assassin hero that punishes low-HP targets and thrives in pickoff-heavy skirmishes.",
    primaryAttribute: "Agility",
    role: "Pickoff assassin",
    highlights: ["Blink mobility", "High solo kill threat", "Excellent for snowballing hero advantage"],
  },
  {
    slug: "death-knight",
    name: "Death Knight",
    raceName: "Undead",
    description: "The spine of many Undead strategies, combining tempo mobility with life-preserving coil.",
    primaryAttribute: "Strength",
    role: "Sustain and mobility",
    highlights: ["Death Coil saves", "Aura movement boost", "Reliable first-hero safety"],
  },
  {
    slug: "lich",
    name: "Lich",
    raceName: "Undead",
    description: "The damage amplifier that turns modest fiend counts into lethal timing pushes.",
    primaryAttribute: "Intelligence",
    role: "Burst finisher",
    highlights: ["Nova nuke threat", "Orb scaling", "Core to tier-two pressure"],
  },
  {
    slug: "dread-lord",
    name: "Dread Lord",
    raceName: "Undead",
    description: "A control-oriented Undead hero that pressures tempo with sleep, tankiness, and punishing melee disruption.",
    primaryAttribute: "Strength",
    role: "Control initiator",
    highlights: ["Sleep disables", "Strong ghoul openings", "Durable frontliner with swarm value"],
  },
  {
    slug: "crypt-lord",
    name: "Crypt Lord",
    raceName: "Undead",
    description: "A summon-heavy bruiser hero that adds tankiness, beetle presence, and area disruption to Undead pushes.",
    primaryAttribute: "Strength",
    role: "Summon bruiser",
    highlights: ["Beetle pressure", "Impale control", "Strong versus ranged openings when supported"],
  },
];

export const units: Unit[] = [
  {
    slug: "peasant",
    name: "Peasant",
    raceName: "Human",
    description: "Human worker unit that powers economy, repair play, militia creeping, and emergency base defense.",
    unitType: "Worker",
    tier: "Tier 1",
    food: 1,
    gold: 75,
    lumber: 0,
    strengths: ["Fast militia conversion", "Repairs buildings and mechanical units", "Enables Human expansion patterns"],
    weaknesses: ["Low combat stats outside militia", "Vulnerable to harassment", "Worker losses slow tech and production"],
  },
  {
    slug: "footman",
    name: "Footman",
    raceName: "Human",
    description: "Foundational Human frontline unit used to scout, creep, and absorb damage in the early game.",
    unitType: "Melee",
    tier: "Tier 1",
    food: 2,
    gold: 135,
    lumber: 0,
    strengths: ["Affordable frontline", "Defend upgrade utility", "Good early map presence"],
    weaknesses: ["Falls off in late-game scaling", "Struggles against heavy magic and siege", "Needs support to stay relevant"],
  },
  {
    slug: "rifleman",
    name: "Rifleman",
    raceName: "Human",
    description: "Reliable ranged backbone for Human midgame armies.",
    unitType: "Ranged",
    tier: "Tier 1",
    food: 3,
    gold: 205,
    lumber: 30,
    strengths: ["Strong sustained damage", "Simple control requirements", "Scales well with caster support"],
    weaknesses: ["Vulnerable to heavy melee surrounds", "Needs frontline protection"],
  },
  {
    slug: "mortar-team",
    name: "Mortar Team",
    raceName: "Human",
    description: "Siege-focused Human artillery that breaks fortified positions and punishes clustered ranged lines.",
    unitType: "Siege",
    tier: "Tier 2",
    food: 3,
    gold: 180,
    lumber: 70,
    strengths: ["Excellent anti-building damage", "Splash versus light ground units", "Strong with human vision control"],
    weaknesses: ["Fragile and slow", "Needs screening to fire safely", "Weak when dived by mobile melee"],
  },
  {
    slug: "priest",
    name: "Priest",
    raceName: "Human",
    description: "Core Human support caster that keeps armies healthy and removes enemy magic through dispel.",
    unitType: "Support Caster",
    tier: "Tier 2",
    food: 2,
    gold: 135,
    lumber: 10,
    strengths: ["Reliable healing", "Dispel utility", "Efficient long fights"],
    weaknesses: ["Mana-dependent", "Low durability", "Poor alone without a damage core"],
  },
  {
    slug: "sorceress",
    name: "Sorceress",
    raceName: "Human",
    description: "Utility caster that slows enemy armies and helps Human ranged cores maintain safe spacing.",
    unitType: "Support Caster",
    tier: "Tier 2",
    food: 2,
    gold: 155,
    lumber: 20,
    strengths: ["Strong slow control", "Excellent kiting support", "Great in rifle-caster compositions"],
    weaknesses: ["Fragile", "Low direct damage", "Requires good positioning and mana management"],
  },
  {
    slug: "spell-breaker",
    name: "Spell Breaker",
    raceName: "Human",
    description: "Anti-caster Human frontline unit that steals buffs and stabilizes midgame spell wars.",
    unitType: "Anti-Magic Melee",
    tier: "Tier 2",
    food: 3,
    gold: 215,
    lumber: 30,
    strengths: ["Spell immunity", "Steals key buffs", "Solid versus caster-heavy armies"],
    weaknesses: ["Low raw damage", "Limited burst", "Less effective versus pure physical armies"],
  },
  {
    slug: "dragonhawk-rider",
    name: "Dragonhawk Rider",
    raceName: "Human",
    description: "Specialist flying unit that controls the air with shackles and supports late-game Human tech switches.",
    unitType: "Flying Utility",
    tier: "Tier 2",
    food: 3,
    gold: 200,
    lumber: 30,
    strengths: ["Aerial shackles utility", "Strong anti-air support", "Useful versus big tech units"],
    weaknesses: ["Expensive", "Needs protection from anti-air focus", "Awkward in low-upkeep skirmishes"],
  },
  {
    slug: "flying-machine",
    name: "Flying Machine",
    raceName: "Human",
    description: "Cheap mechanical flier that provides scouting, anti-air swarms, and map control.",
    unitType: "Flying Utility",
    tier: "Tier 2",
    food: 1,
    gold: 90,
    lumber: 30,
    strengths: ["Fast scouting", "Cheap anti-air volume", "Good map vision and harassment coverage"],
    weaknesses: ["Very fragile", "Low ground impact", "Weak if overproduced into wrong matchup"],
  },
  {
    slug: "knight",
    name: "Knight",
    raceName: "Human",
    description: "Heavy cavalry finisher that gives Human a durable melee anchor in longer tech games.",
    unitType: "Heavy Melee",
    tier: "Tier 3",
    food: 4,
    gold: 245,
    lumber: 60,
    strengths: ["Durable frontline", "Strong upgrades", "Scales well into late game"],
    weaknesses: ["Expensive tech path", "Susceptible to focus without support", "Slow to reach critical mass"],
  },
  {
    slug: "siege-engine",
    name: "Siege Engine",
    raceName: "Human",
    description: "Mechanical siege tank that punishes static defense, expansions, and poorly defended economies.",
    unitType: "Siege",
    tier: "Tier 2",
    food: 4,
    gold: 195,
    lumber: 60,
    strengths: ["Massive building damage", "Durable mechanical body", "Strong in split-pressure play"],
    weaknesses: ["Limited anti-unit value", "Slow", "Requires map control to justify cost"],
  },
  {
    slug: "peon",
    name: "Peon",
    raceName: "Orc",
    description: "Orc worker that fuels Burrow economy, repairs, and can body-block or scout in the early game.",
    unitType: "Worker",
    tier: "Tier 1",
    food: 1,
    gold: 75,
    lumber: 0,
    strengths: ["Sturdy worker body", "Repairs key structures", "Useful for scouting and emergency tower play"],
    weaknesses: ["Low combat power", "Worker losses hurt tech tempo", "Vulnerable while building expansions"],
  },
  {
    slug: "grunt",
    name: "Grunt",
    raceName: "Orc",
    description: "Classic Orc frontline unit that supports hero pressure and anchors early map control.",
    unitType: "Melee",
    tier: "Tier 1",
    food: 3,
    gold: 200,
    lumber: 0,
    strengths: ["Durable early body", "Strong with hero focus fire", "Simple and reliable opening unit"],
    weaknesses: ["Can be kited", "Falls off without upgrades or support", "Limited utility on its own"],
  },
  {
    slug: "headhunter",
    name: "Headhunter",
    raceName: "Orc",
    description: "Ranged Orc damage dealer that transitions into Berserker form for high DPS timing attacks.",
    unitType: "Ranged",
    tier: "Tier 1",
    food: 2,
    gold: 140,
    lumber: 20,
    strengths: ["Efficient ranged damage", "Strong Berserker upgrade", "Excellent with Bloodlust and healing"],
    weaknesses: ["Fragile compared to Grunts", "Needs support to survive dives", "Can feed experience if mispositioned"],
  },
  {
    slug: "raider",
    name: "Raider",
    raceName: "Orc",
    description: "A utility cavalry unit built around ensnare and structural pressure.",
    unitType: "Melee Utility",
    tier: "Tier 2",
    food: 3,
    gold: 180,
    lumber: 40,
    strengths: ["Excellent at catches", "Great for surrounds", "Punishes exposed expansions"],
    weaknesses: ["Falls off in raw combat value without support", "Can overextend easily"],
  },
  {
    slug: "kodo-beast",
    name: "Kodo Beast",
    raceName: "Orc",
    description: "Aura-support utility beast that amplifies Orc armies and threatens key devours in fights.",
    unitType: "Support Beast",
    tier: "Tier 2",
    food: 4,
    gold: 255,
    lumber: 60,
    strengths: ["War Drums aura", "Devour utility", "Excellent support for ranged Orc armies"],
    weaknesses: ["Expensive support slot", "Large target", "Weak if sniped before impact"],
  },
  {
    slug: "wind-rider",
    name: "Wind Rider",
    raceName: "Orc",
    description: "High-damage flying attacker used for hit-and-run timings and punishing exposed targets.",
    unitType: "Flying Ranged",
    tier: "Tier 2",
    food: 3,
    gold: 265,
    lumber: 40,
    strengths: ["Heavy burst damage", "Great versus isolated units", "Strong air timing potential"],
    weaknesses: ["Very fragile", "Punished by dedicated anti-air", "Needs careful focus fire control"],
  },
  {
    slug: "shaman",
    name: "Shaman",
    raceName: "Orc",
    description: "Orc support caster that brings purge, Bloodlust, and anti-summon pressure.",
    unitType: "Support Caster",
    tier: "Tier 2",
    food: 2,
    gold: 130,
    lumber: 20,
    strengths: ["Purge utility", "Bloodlust scaling", "Useful versus summons and mobility heroes"],
    weaknesses: ["Mana hungry", "Low durability", "Slow to matter without upgrades"],
  },
  {
    slug: "witch-doctor",
    name: "Witch Doctor",
    raceName: "Orc",
    description: "Vision and sustain support caster built around wards and positional map control.",
    unitType: "Support Caster",
    tier: "Tier 2",
    food: 2,
    gold: 145,
    lumber: 25,
    strengths: ["Healing Ward", "Sentry map vision", "Stasis punishes careless movement"],
    weaknesses: ["Fragile", "Ward reliance", "Low direct combat impact"],
  },
  {
    slug: "spirit-walker",
    name: "Spirit Walker",
    raceName: "Orc",
    description: "Dispel-capable support unit that links Orc armies together for durable tier-two and tier-three fights.",
    unitType: "Support Caster",
    tier: "Tier 2",
    food: 2,
    gold: 195,
    lumber: 35,
    strengths: ["Disenchant", "Spirit Link durability", "Solid anti-magic utility"],
    weaknesses: ["Expensive upgrades", "Limited damage", "Needs army value around it"],
  },
  {
    slug: "tauren",
    name: "Tauren",
    raceName: "Orc",
    description: "Massive late-game bruiser that dominates extended fights once Orc reaches deep tech.",
    unitType: "Heavy Melee",
    tier: "Tier 3",
    food: 5,
    gold: 280,
    lumber: 80,
    strengths: ["Extreme durability", "Huge melee damage", "Powerful with Spirit Link and Bloodlust"],
    weaknesses: ["Very expensive", "Slow to reach", "Punished before critical mass"],
  },
  {
    slug: "demolisher",
    name: "Demolisher",
    raceName: "Orc",
    description: "Orc artillery piece that breaks expansions and punishes static defenses from range.",
    unitType: "Siege",
    tier: "Tier 2",
    food: 4,
    gold: 220,
    lumber: 50,
    strengths: ["High siege damage", "Good range", "Threatens turtling opponents"],
    weaknesses: ["Fragile when caught", "Slow repositioning", "Poor without frontline protection"],
  },
  {
    slug: "troll-batrider",
    name: "Troll Batrider",
    raceName: "Orc",
    description: "Disposable anti-air flier that trades itself for tempo and punishes stacked air units.",
    unitType: "Flying Utility",
    tier: "Tier 2",
    food: 2,
    gold: 160,
    lumber: 40,
    strengths: ["Explosive anti-air trade", "Fast harassment", "Useful against greedy air tech"],
    weaknesses: ["Self-destructive value pattern", "Low general-purpose combat power", "Weak versus spread armies"],
  },
  {
    slug: "acolyte",
    name: "Acolyte",
    raceName: "Undead",
    description: "Undead worker that powers blight structures, haunted gold mines, and repair-free base growth.",
    unitType: "Worker",
    tier: "Tier 1",
    food: 1,
    gold: 75,
    lumber: 0,
    strengths: ["Safe blight economy", "Can summon buildings without walking off base", "Supports haunted expansion patterns"],
    weaknesses: ["Very fragile", "Worker losses are painful", "Poor scouting and map presence"],
  },
  {
    slug: "ghoul",
    name: "Ghoul",
    raceName: "Undead",
    description: "Fast melee Undead unit used for early lumber, surrounds, and aggressive tempo builds.",
    unitType: "Melee",
    tier: "Tier 1",
    food: 2,
    gold: 120,
    lumber: 0,
    strengths: ["Fast movement", "Good early surround pressure", "Double as lumber workers"],
    weaknesses: ["Fragile", "Scale poorly without support", "Feed experience if traded badly"],
  },
  {
    slug: "crypt-fiend",
    name: "Crypt Fiend",
    raceName: "Undead",
    description: "The staple ranged control unit for many Undead core compositions.",
    unitType: "Ranged",
    tier: "Tier 1",
    food: 3,
    gold: 215,
    lumber: 40,
    strengths: ["High single-target damage", "Web utility", "Strong orb timing support"],
    weaknesses: ["Fragile when isolated", "Relies on statue sustain"],
  },
  {
    slug: "gargoyle",
    name: "Gargoyle",
    raceName: "Undead",
    description: "Fast anti-air and harassment flier that gives Undead mobility and map pressure.",
    unitType: "Flying Ranged",
    tier: "Tier 2",
    food: 2,
    gold: 185,
    lumber: 30,
    strengths: ["Excellent anti-air swarms", "Fast map mobility", "Good worker and expansion harassment"],
    weaknesses: ["Weak against strong splash or dedicated anti-air", "Can be supply-inefficient in bad fights"],
  },
  {
    slug: "abomination",
    name: "Abomination",
    raceName: "Undead",
    description: "Heavy Undead frontline monster that anchors fiend and destroyer armies in longer fights.",
    unitType: "Heavy Melee",
    tier: "Tier 3",
    food: 4,
    gold: 240,
    lumber: 70,
    strengths: ["Durable body", "Disease cloud pressure", "Strong meat shield for ranged cores"],
    weaknesses: ["Slow", "Large target", "Needs statue sustain and positioning"],
  },
  {
    slug: "necromancer",
    name: "Necromancer",
    raceName: "Undead",
    description: "Summon-based support caster that turns static defenses and prolonged pushes into attrition battles.",
    unitType: "Support Caster",
    tier: "Tier 2",
    food: 2,
    gold: 145,
    lumber: 20,
    strengths: ["Skeleton pressure", "Great in siege scenarios", "Can overwhelm unprepared defenses"],
    weaknesses: ["Mana dependent", "Countered by dispel", "Weak in fast skirmishes"],
  },
  {
    slug: "banshee",
    name: "Banshee",
    raceName: "Undead",
    description: "Undead support caster that reduces enemy damage and threatens high-swing possession plays.",
    unitType: "Support Caster",
    tier: "Tier 2",
    food: 2,
    gold: 155,
    lumber: 30,
    strengths: ["Curse utility", "Anti-physical value", "Possession win condition"],
    weaknesses: ["Expensive upgrades", "Fragile", "Slow tempo without mana support"],
  },
  {
    slug: "meat-wagon",
    name: "Meat Wagon",
    raceName: "Undead",
    description: "Siege support vehicle that enables Undead base cracking and sustained necromancer pressure.",
    unitType: "Siege",
    tier: "Tier 2",
    food: 4,
    gold: 230,
    lumber: 50,
    strengths: ["Strong siege damage", "Supports corpse-based strategies", "Useful versus fortified bases"],
    weaknesses: ["Slow", "Fragile when exposed", "Weak without a supporting composition"],
  },
  {
    slug: "obsidian-statue",
    name: "Obsidian Statue",
    raceName: "Undead",
    description: "Signature Undead support unit that keeps mana and health flowing during timing pushes.",
    unitType: "Support",
    tier: "Tier 2",
    food: 3,
    gold: 200,
    lumber: 35,
    strengths: ["Excellent sustain", "Critical for fiend and hero pressure", "Transforms fights through attrition"],
    weaknesses: ["Low combat stats", "Prime focus target", "Vulnerable if left unprotected"],
  },
  {
    slug: "destroyer",
    name: "Destroyer",
    raceName: "Undead",
    description: "Airborne anti-magic finisher converted from statues to break summons and punish casters.",
    unitType: "Flying Anti-Magic",
    tier: "Tier 3",
    food: 5,
    gold: 0,
    lumber: 0,
    strengths: ["Devour Magic", "Strong spell resistance", "High value versus caster-heavy armies"],
    weaknesses: ["Consumes statue economy", "Can be focus-fired by dedicated anti-air", "Expensive to field repeatedly"],
  },
  {
    slug: "frost-wyrm",
    name: "Frost Wyrm",
    raceName: "Undead",
    description: "Massive late-game air terror that slows targets and dominates fights if unsupported anti-air is lacking.",
    unitType: "Heavy Flying",
    tier: "Tier 3",
    food: 7,
    gold: 385,
    lumber: 120,
    strengths: ["Huge damage", "Frost attack slow", "Excellent siege and late-game air dominance"],
    weaknesses: ["Very expensive", "Slow to tech to", "Hard-punished by focused anti-air"],
  },
  {
    slug: "wisp",
    name: "Wisp",
    raceName: "Night Elf",
    description: "Night Elf worker that scouts efficiently, powers entangled bases, and provides detonate utility.",
    unitType: "Worker",
    tier: "Tier 1",
    food: 1,
    gold: 60,
    lumber: 0,
    strengths: ["Detonate anti-magic utility", "Fast scouting", "Safe tree-based economy support"],
    weaknesses: ["Very fragile", "Low direct combat value", "Worker losses disrupt moonwell and tech flow"],
  },
  {
    slug: "archer",
    name: "Archer",
    raceName: "Night Elf",
    description: "Fast ranged opener that supports creeping, map pressure, and focused hero harassment.",
    unitType: "Ranged",
    tier: "Tier 1",
    food: 2,
    gold: 130,
    lumber: 10,
    strengths: ["Good early ranged DPS", "Flexible openers", "Mobile with Night Elf tempo play"],
    weaknesses: ["Fragile", "Needs hero support", "Can feed experience when overproduced"],
  },
  {
    slug: "huntress",
    name: "Huntress",
    raceName: "Night Elf",
    description: "Durable early pressure unit that controls map space and punishes exposed workers and light units.",
    unitType: "Melee",
    tier: "Tier 1",
    food: 3,
    gold: 195,
    lumber: 20,
    strengths: ["Strong early map control", "Bouncing attack", "Durable for tier-one pressure"],
    weaknesses: ["Falls off without transitions", "Weak against focused piercing damage", "Can be kited by tech armies"],
  },
  {
    slug: "glaive-thrower",
    name: "Glaive Thrower",
    raceName: "Night Elf",
    description: "Night Elf siege unit used to break buildings and punish static defensive positions.",
    unitType: "Siege",
    tier: "Tier 1",
    food: 3,
    gold: 155,
    lumber: 65,
    strengths: ["Strong anti-building damage", "Useful in push timings", "Combines well with map-control openers"],
    weaknesses: ["Fragile", "Slow repositioning", "Limited direct combat value"],
  },
  {
    slug: "dryad",
    name: "Dryad",
    raceName: "Night Elf",
    description: "Mobile anti-magic ranged unit that gives Night Elf dispel, poison pressure, and fast repositioning.",
    unitType: "Ranged Utility",
    tier: "Tier 2",
    food: 3,
    gold: 145,
    lumber: 60,
    strengths: ["Abolish Magic", "Fast movement", "Poison utility and kiting"],
    weaknesses: ["Low burst", "Fragile when surrounded", "Needs frontline support"],
  },
  {
    slug: "druid-of-the-claw",
    name: "Druid of the Claw",
    raceName: "Night Elf",
    description: "The bear form frontline that anchors many Night Elf timing pushes.",
    unitType: "Melee Caster",
    tier: "Tier 2",
    food: 4,
    gold: 255,
    lumber: 80,
    strengths: ["Durable frontline", "Roar scaling", "Strong sustained fights"],
    weaknesses: ["Expensive", "Timing-sensitive before master training"],
  },
  {
    slug: "druid-of-the-talon",
    name: "Druid of the Talon",
    raceName: "Night Elf",
    description: "Caster-support unit that enables cyclone control and mobile Night Elf spell-based styles.",
    unitType: "Support Caster",
    tier: "Tier 2",
    food: 2,
    gold: 135,
    lumber: 20,
    strengths: ["Cyclone control", "Faerie Fire utility", "Excellent disruption in hero-centric battles"],
    weaknesses: ["Fragile", "Mana hungry", "Weak if caught without positioning"],
  },
  {
    slug: "mountain-giant",
    name: "Mountain Giant",
    raceName: "Night Elf",
    description: "Huge taunt-based frontline unit used to soak damage and create space for fragile Night Elf backlines.",
    unitType: "Heavy Melee",
    tier: "Tier 3",
    food: 7,
    gold: 425,
    lumber: 100,
    strengths: ["Extreme durability", "Taunt utility", "Great space-making body"],
    weaknesses: ["Low direct DPS", "Expensive", "Needs support to convert durability into wins"],
  },
  {
    slug: "hippogryph",
    name: "Hippogryph",
    raceName: "Night Elf",
    description: "Fast anti-air creature that gives Night Elf flexible map control and rider options.",
    unitType: "Flying Utility",
    tier: "Tier 2",
    food: 2,
    gold: 160,
    lumber: 20,
    strengths: ["Good anti-air mobility", "Can pair with archers", "Fast map coverage"],
    weaknesses: ["Limited ground impact", "Vulnerable to strong anti-air focus", "Awkward when overbuilt"],
  },
  {
    slug: "faerie-dragon",
    name: "Faerie Dragon",
    raceName: "Night Elf",
    description: "Magic-resistant flier that punishes casters and provides strong utility in spell-heavy matchups.",
    unitType: "Flying Utility",
    tier: "Tier 2",
    food: 3,
    gold: 155,
    lumber: 40,
    strengths: ["Strong versus casters", "Phase Shift survivability", "Excellent disruption value"],
    weaknesses: ["Low raw damage", "Niche role", "Can underperform versus pure physical armies"],
  },
  {
    slug: "chimaera",
    name: "Chimaera",
    raceName: "Night Elf",
    description: "Late-game siege flier that crushes buildings and heavy ground when protected.",
    unitType: "Heavy Flying",
    tier: "Tier 3",
    food: 7,
    gold: 330,
    lumber: 70,
    strengths: ["Massive siege damage", "Dominant versus static positions", "High late-game threat"],
    weaknesses: ["Expensive", "No air attack", "Punished by dedicated anti-air focus"],
  },
  {
    slug: "goblin-sapper",
    name: "Goblin Sapper",
    raceName: "Neutral",
    description: "Disposable demolition unit from the Goblin Laboratory used for explosive worker and building punish windows.",
    unitType: "Neutral Utility",
    tier: "Neutral",
    food: 2,
    gold: 215,
    lumber: 0,
    strengths: ["Huge burst versus buildings", "Surprise timing potential", "Excellent expansion punish tool"],
    weaknesses: ["Single-use", "Requires precise timing", "Low value if scouted early"],
  },
  {
    slug: "goblin-zeppelin",
    name: "Goblin Zeppelin",
    raceName: "Neutral",
    description: "Transport airship that unlocks drops, rescues, and terrain-based movement tricks for every race.",
    unitType: "Neutral Utility",
    tier: "Neutral",
    food: 0,
    gold: 240,
    lumber: 0,
    strengths: ["Drop play", "Unit rescue utility", "Creative map mobility"],
    weaknesses: ["No combat power", "Vulnerable to anti-air", "High positional risk if lost loaded"],
  },
  {
    slug: "goblin-shredder",
    name: "Goblin Shredder",
    raceName: "Neutral",
    description: "Powerful neutral worker-combat hybrid prized for lumber efficiency and surprising early damage output.",
    unitType: "Neutral Utility",
    tier: "Neutral",
    food: 4,
    gold: 375,
    lumber: 0,
    strengths: ["Massive lumber income", "Strong early combat body", "High value pickup on many maps"],
    weaknesses: ["Expensive neutral purchase", "Can be focused down", "Occupies supply in tight builds"],
  },
  {
    slug: "forest-troll-shadow-priest",
    name: "Forest Troll Shadow Priest",
    raceName: "Neutral",
    description: "Mercenary support caster that adds healing and dispel to races that need early sustain or anti-summon tools.",
    unitType: "Neutral Caster",
    tier: "Neutral",
    food: 2,
    gold: 195,
    lumber: 0,
    strengths: ["Healing utility", "Dispel option", "Useful flexible mercenary support"],
    weaknesses: ["Fragile", "Mana limited", "Dependent on merc camp access"],
  },
  {
    slug: "forest-troll-berserker",
    name: "Forest Troll Berserker",
    raceName: "Neutral",
    description: "High-damage ranged mercenary pickup that strengthens timing attacks and camp-control fights.",
    unitType: "Neutral Ranged",
    tier: "Neutral",
    food: 3,
    gold: 245,
    lumber: 0,
    strengths: ["Strong ranged DPS", "Immediate merc camp power spike", "Simple high-impact pickup"],
    weaknesses: ["Fragile", "Can be expensive to sustain", "No advanced utility beyond damage"],
  },
  {
    slug: "mud-golem",
    name: "Mud Golem",
    raceName: "Neutral",
    description: "Durable mercenary support unit known for ranged slow utility in camp and tavern-heavy maps.",
    unitType: "Neutral Utility",
    tier: "Neutral",
    food: 3,
    gold: 235,
    lumber: 0,
    strengths: ["Slow utility", "Sturdy mercenary body", "Good tempo value on contested maps"],
    weaknesses: ["Niche availability", "Low scaling late", "Awkward if the matchup demands mobility"],
  },
  {
    slug: "ogre-mauler",
    name: "Ogre Mauler",
    raceName: "Neutral",
    description: "Heavy neutral mercenary bruiser that adds raw frontline stats in merc-camp timing pushes.",
    unitType: "Neutral Melee",
    tier: "Neutral",
    food: 4,
    gold: 255,
    lumber: 0,
    strengths: ["Durable body", "Simple frontline power", "Good immediate merc camp value"],
    weaknesses: ["Low utility", "Can be kited", "Poor long-term scaling compared with race tech"],
  },
  {
    slug: "dark-troll-trapper",
    name: "Dark Troll Trapper",
    raceName: "Neutral",
    description: "Ranged mercenary with ensnare utility that creates catches and surround opportunities for many styles.",
    unitType: "Neutral Ranged Utility",
    tier: "Neutral",
    food: 2,
    gold: 195,
    lumber: 0,
    strengths: ["Ensnare utility", "Good tempo pickup", "Useful versus mobility and air"],
    weaknesses: ["Fragile", "Map dependent", "Low value if fights stay front-to-back"],
  },
  {
    slug: "furbolg-tracker",
    name: "Furbolg Tracker",
    raceName: "Neutral",
    description: "Solid ranged mercenary option that adds immediate damage and map-presence value from merc camps.",
    unitType: "Neutral Ranged",
    tier: "Neutral",
    food: 3,
    gold: 225,
    lumber: 0,
    strengths: ["Immediate ranged power", "Good merc timing filler", "Simple efficient statline"],
    weaknesses: ["Little utility", "Falls off versus teched armies", "Camp dependent"],
  },
];

export const maps: MapGuide[] = [
  {
    slug: "echo-isles",
    name: "Echo Isles",
    description: "A compact map with fast skirmish timings and contestable merchant play.",
    creepNotes: "Small camp routes accelerate first-hero tempo for all races.",
    expansionNotes: "Natural expansions can be pressured quickly if scouting is weak.",
  },
  {
    slug: "northern-isles",
    name: "Northern Isles",
    description: "A standard ladder map with balanced creep access and multiple attack lanes.",
    creepNotes: "Green into orange camp routing is flexible and easy to contest.",
    expansionNotes: "Expansions are practical but require vision against timing attacks.",
  },
  {
    slug: "concealed-hill",
    name: "Concealed Hill",
    description: "A larger map that rewards map control and disciplined expansion timing.",
    creepNotes: "Wide creep spread favors scouting and mobility.",
    expansionNotes: "Strong expansion potential for players who control central movement.",
  },
];

export const matchups: Matchup[] = [
  {
    slug: "orc-vs-human",
    title: "Orc vs Human",
    summary: "Orc wants to destabilize Human before the economy and caster backbone start snowballing.",
    difficulty: "Demanding",
    earlyGamePlan: "Scout for fast expansion and force peasant losses without overcommitting.",
    midGamePlan: "Hit raider-shadow hunter timing before Human reaches comfortable breaker-caster counts.",
    lateGamePlan: "Stay mobile, isolate human reinforcements, and avoid fighting deep into fortified bases.",
    commonMistakes: [
      "Trading Blademaster health for low-value worker hits",
      "Allowing free level-three Archmage timing",
      "Taking head-on fights into superior Human positioning",
    ],
    heroChoices: ["Blademaster", "Shadow Hunter", "Tauren Chieftain"],
  },
  {
    slug: "human-vs-undead",
    title: "Human vs Undead",
    summary: "Human needs disciplined creeping and a measured expansion plan against Undead's tier-two spikes.",
    difficulty: "High pressure",
    earlyGamePlan: "Protect peasants, deny free fiend creeping, and route militia for safe map progress.",
    midGamePlan: "Pressure statues and hold formation so storm bolt and rifles can punish overextension.",
    lateGamePlan: "Use production depth and healing to outlast smaller Undead armies in longer trades.",
    commonMistakes: [
      "Expanding without scout confirmation",
      "Misusing militia and losing early economy",
      "Taking fights before critical dispel or bolt timing",
    ],
    heroChoices: ["Archmage", "Mountain King", "Paladin"],
  },
  {
    slug: "night-elf-vs-undead",
    title: "Night Elf vs Undead",
    summary: "Night Elf plays for map control and unit preservation while Undead hunts a clean timing attack.",
    difficulty: "Tight margins",
    earlyGamePlan: "Contest fiend creeping and use moonwell-backed skirmishes to limit DK freedom.",
    midGamePlan: "Choose either bears for durability or talons for control before Undead reaches ideal statues and orb.",
    lateGamePlan: "Split push, re-engage on positioning mistakes, and avoid feeding hero levels to nova focus.",
    commonMistakes: [
      "Over-chasing fiends near statues",
      "Taking direct fights without mana advantage",
      "Skipping scouting around destroyer timing",
    ],
    heroChoices: ["Demon Hunter", "Keeper of the Grove", "Naga Sea Witch"],
  },
  {
    slug: "undead-vs-orc",
    title: "Undead vs Orc",
    summary: "Undead must preserve fiends and hero experience long enough to punish Orc's midgame commitment.",
    difficulty: "Execution heavy",
    earlyGamePlan: "Creep safely, deny Blademaster value, and protect your first statue timing.",
    midGamePlan: "Use coil-nova threat to punish raider overextensions and control item-rich map pockets.",
    lateGamePlan: "Scale orb and destroyers only when the game state supports them rather than autopiloting tech.",
    commonMistakes: [
      "Losing fiends during the first scouting skirmish",
      "Taking fights before Lich or orb timing",
      "Underestimating hex around statue positioning",
    ],
    heroChoices: ["Death Knight", "Lich", "Dark Ranger"],
  },
];

export const builds: Build[] = [
  {
    slug: "orc-grunt-raider-shadow-hunter",
    title: "Orc Grunt Raider Shadow Hunter",
    raceName: "Orc",
    raceSlug: "orc",
    summary: "A stable Orc ladder opening built to pressure Human and exploit exposed expansions.",
    difficulty: "Intermediate",
    strategyType: "Tempo Midgame",
    matchupSlug: "orc-vs-human",
    steps: [
      { stepNumber: 1, supply: 6, timing: "0:00", instruction: "Queue peons, altar, burrow, and start scouting for expansion greed." },
      { stepNumber: 2, supply: 18, timing: "1:40", instruction: "Creep efficiently with Blademaster while preserving grunt hit points for the first skirmish." },
      { stepNumber: 3, supply: 28, timing: "3:10", instruction: "Tech to tier two and evaluate whether Human is fast expanding or defending." },
      { stepNumber: 4, supply: 40, timing: "5:15", instruction: "Add Shadow Hunter, bestiary, and secure raider timing for a power spike fight." },
    ],
  },
  {
    slug: "human-rifle-caster-expand",
    title: "Human Rifle Caster Expand",
    raceName: "Human",
    raceSlug: "human",
    summary: "A disciplined Human expansion build that leans on militia efficiency and caster scaling.",
    difficulty: "Intermediate",
    strategyType: "Economic Control",
    matchupSlug: "human-vs-undead",
    steps: [
      { stepNumber: 1, supply: 6, timing: "0:00", instruction: "Open altar and farm, then route peasants for a minimal-loss first creep." },
      { stepNumber: 2, supply: 20, timing: "2:00", instruction: "Commit to expansion timing only if scouting confirms manageable pressure." },
      { stepNumber: 3, supply: 28, timing: "3:40", instruction: "Begin tech and set up blacksmith plus arcane sanctums for stable rifle-caster play." },
      { stepNumber: 4, supply: 42, timing: "6:00", instruction: "Anchor fights around storm bolt and priest sustain rather than chasing deep." },
    ],
  },
  {
    slug: "night-elf-demon-hunter-bears",
    title: "Night Elf Demon Hunter Bears",
    raceName: "Night Elf",
    raceSlug: "night-elf",
    summary: "A resilient Night Elf route that aims for strong sustained fights with bear transitions.",
    difficulty: "Advanced",
    strategyType: "Sustain Timing",
    matchupSlug: "night-elf-vs-undead",
    steps: [
      { stepNumber: 1, supply: 5, timing: "0:00", instruction: "Open with a demon hunter and optimize moonwell usage for early map control." },
      { stepNumber: 2, supply: 20, timing: "2:10", instruction: "Creep safely while contesting the opponent's easiest experience routes." },
      { stepNumber: 3, supply: 30, timing: "4:20", instruction: "Tech quickly, add a second hero, and prepare lore timing into bears." },
      { stepNumber: 4, supply: 46, timing: "7:00", instruction: "Fight only after master training progress supports long engagements." },
    ],
  },
  {
    slug: "undead-dk-lich-fiends",
    title: "Undead DK Lich Fiends",
    raceName: "Undead",
    raceSlug: "undead",
    summary: "A classic Undead timing route that prioritizes fiend count, statue sustain, and burst damage.",
    difficulty: "Intermediate",
    strategyType: "Timing Push",
    matchupSlug: "undead-vs-orc",
    steps: [
      { stepNumber: 1, supply: 5, timing: "0:00", instruction: "Open crypt and altar with a safe acolyte pattern that minimizes early disruption risk." },
      { stepNumber: 2, supply: 20, timing: "2:00", instruction: "Creep efficiently with Death Knight and avoid exposing fiends to unnecessary focus." },
      { stepNumber: 3, supply: 30, timing: "4:00", instruction: "Tech to tier two, add Lich, and finish the first statue before extended fights." },
      { stepNumber: 4, supply: 42, timing: "6:10", instruction: "Use coil-nova and orb timing to force a fight before the opponent is fully stabilized." },
    ],
  },
];

export const favoriteBuilds = builds.slice(0, 3);
