import type { Build, Hero, MapGuide, Matchup, Race, Unit } from "./types";

export const races: Race[] = [
  {
    slug: "human",
    name: "Human",
    badge: "Alliance Discipline",
    identity: "Flexible macro with strong expansion timings and layered spell support.",
    description:
      "Human wins by stabilizing early creep routes, protecting economy, and turning precise caster support into decisive tempo swings.",
    strengths: ["Militia-assisted map control", "Safe expansions", "Strong late-game spell utility"],
    signatureHeroes: ["Archmage", "Mountain King", "Paladin"],
    ladderFocus: "Secure creeping routes, preserve peasants, and expand on favorable map flow.",
  },
  {
    slug: "orc",
    name: "Orc",
    badge: "Iron Horde Tempo",
    identity: "Explosive skirmishing backed by durable units and high-value hero pressure.",
    description:
      "Orc thrives when it dictates the pace with hero focus fire, clean itemization, and a transition that lands before the opponent stabilizes.",
    strengths: ["Early hero pressure", "Efficient tier-two timing", "Excellent focus fire"],
    signatureHeroes: ["Blademaster", "Far Seer", "Shadow Hunter"],
    ladderFocus: "Force reactions, scout constantly, and punish greedy tech or expansion patterns.",
  },
  {
    slug: "night-elf",
    name: "Night Elf",
    badge: "Moonwell Control",
    identity: "Mobility, map pressure, and high-upkeep avoidance through tempo-sensitive play.",
    description:
      "Night Elf leverages map presence, healing efficiency, and adaptable hero compositions to stretch opponents across multiple fronts.",
    strengths: ["Map mobility", "Sustain through Moon Wells", "Tactical tech switches"],
    signatureHeroes: ["Demon Hunter", "Keeper of the Grove", "Warden"],
    ladderFocus: "Creep efficiently, deny safe expansions, and convert mobility into resource advantages.",
  },
  {
    slug: "undead",
    name: "Undead",
    badge: "Necropolis Pressure",
    identity: "Precise creeping, punishing timing attacks, and elite ranged damage backed by statues.",
    description:
      "Undead rewards players who protect fragile unit counts early, hit core timing windows, and convert superior hero leveling into map control.",
    strengths: ["Reliable nuke damage", "Strong timing pushes", "Efficient sustain with statues"],
    signatureHeroes: ["Death Knight", "Lich", "Crypt Lord"],
    ladderFocus: "Keep experience flowing, protect fiend numbers, and decide when to all-in versus expand.",
  },
];

export const heroes: Hero[] = [
  {
    slug: "archmage",
    name: "Archmage",
    raceName: "Human",
    description: "A macro enabler whose brilliance aura and summons unlock Human's most stable openings.",
    primaryAttribute: "Intelligence",
    role: "Tempo support",
    highlights: ["Smooth early creeping", "Improves caster mana economy", "Reliable expansion partner"],
  },
  {
    slug: "mountain-king",
    name: "Mountain King",
    raceName: "Human",
    description: "A control-heavy second hero that turns focus fire windows into guaranteed unit kills.",
    primaryAttribute: "Strength",
    role: "Single-target lockdown",
    highlights: ["Storm Bolt pressure", "Frontline durability", "Pairs well with rifles and casters"],
  },
  {
    slug: "blademaster",
    name: "Blademaster",
    raceName: "Orc",
    description: "The classic Orc carry hero built around scouting, item scaling, and punishing exposed targets.",
    primaryAttribute: "Agility",
    role: "Harass carry",
    highlights: ["Exceptional scouting", "Item-dependent burst", "Forces defensive reactions"],
  },
  {
    slug: "shadow-hunter",
    name: "Shadow Hunter",
    raceName: "Orc",
    description: "The stabilizer behind Orc's midgame with healing wave sustain and hex control.",
    primaryAttribute: "Intelligence",
    role: "Backline support",
    highlights: ["Healing Wave sustain", "Hex for hero catches", "Improves grunts and raiders longevity"],
  },
  {
    slug: "demon-hunter",
    name: "Demon Hunter",
    raceName: "Night Elf",
    description: "A mana denial specialist that keeps enemy heroes honest while anchoring mobile skirmishes.",
    primaryAttribute: "Agility",
    role: "Anti-caster duelist",
    highlights: ["Mana Burn pressure", "High mobility", "Excellent frontline scaling"],
  },
  {
    slug: "keeper-of-the-grove",
    name: "Keeper of the Grove",
    raceName: "Night Elf",
    description: "A map-control hero that punishes greed and turns entangle into repeated economic damage.",
    primaryAttribute: "Intelligence",
    role: "Map pressure",
    highlights: ["Entangle pickoffs", "Treant creeping", "Strong versus exposed expansions"],
  },
  {
    slug: "death-knight",
    name: "Death Knight",
    raceName: "Undead",
    description: "The spine of many Undead strategies, combining tempo mobility with life-preserving coil.",
    primaryAttribute: "Strength",
    role: "Sustain and mobility",
    highlights: ["Death Coil saves", "Aura movement boost", "Reliable first-hero safety"],
  },
  {
    slug: "lich",
    name: "Lich",
    raceName: "Undead",
    description: "The damage amplifier that turns modest fiend counts into lethal timing pushes.",
    primaryAttribute: "Intelligence",
    role: "Burst finisher",
    highlights: ["Nova nuke threat", "Orb scaling", "Core to tier-two pressure"],
  },
];

export const units: Unit[] = [
  {
    slug: "rifleman",
    name: "Rifleman",
    raceName: "Human",
    description: "Reliable ranged backbone for Human midgame armies.",
    unitType: "Ranged",
    strengths: ["Strong sustained damage", "Simple control requirements", "Scales well with caster support"],
    weaknesses: ["Vulnerable to heavy melee surrounds", "Needs frontline protection"],
  },
  {
    slug: "raider",
    name: "Raider",
    raceName: "Orc",
    description: "A utility cavalry unit built around ensnare and structural pressure.",
    unitType: "Melee Utility",
    strengths: ["Excellent at catches", "Great for surrounds", "Punishes exposed expansions"],
    weaknesses: ["Falls off in raw combat value without support", "Can overextend easily"],
  },
  {
    slug: "druid-of-the-claw",
    name: "Druid of the Claw",
    raceName: "Night Elf",
    description: "The bear form frontline that anchors many Night Elf timing pushes.",
    unitType: "Melee Caster",
    strengths: ["Durable frontline", "Roar scaling", "Strong sustained fights"],
    weaknesses: ["Expensive", "Timing-sensitive before master training"],
  },
  {
    slug: "crypt-fiend",
    name: "Crypt Fiend",
    raceName: "Undead",
    description: "The staple ranged control unit for many Undead core compositions.",
    unitType: "Ranged",
    strengths: ["High single-target damage", "Web utility", "Strong orb timing support"],
    weaknesses: ["Fragile when isolated", "Relies on statue sustain"],
  },
];

export const maps: MapGuide[] = [
  {
    slug: "echo-isles",
    name: "Echo Isles",
    description: "A compact map with fast skirmish timings and contestable merchant play.",
    creepNotes: "Small camp routes accelerate first-hero tempo for all races.",
    expansionNotes: "Natural expansions can be pressured quickly if scouting is weak.",
  },
  {
    slug: "northern-isles",
    name: "Northern Isles",
    description: "A standard ladder map with balanced creep access and multiple attack lanes.",
    creepNotes: "Green into orange camp routing is flexible and easy to contest.",
    expansionNotes: "Expansions are practical but require vision against timing attacks.",
  },
  {
    slug: "concealed-hill",
    name: "Concealed Hill",
    description: "A larger map that rewards map control and disciplined expansion timing.",
    creepNotes: "Wide creep spread favors scouting and mobility.",
    expansionNotes: "Strong expansion potential for players who control central movement.",
  },
];

export const matchups: Matchup[] = [
  {
    slug: "orc-vs-human",
    title: "Orc vs Human",
    summary: "Orc wants to destabilize Human before the economy and caster backbone start snowballing.",
    difficulty: "Demanding",
    earlyGamePlan: "Scout for fast expansion and force peasant losses without overcommitting.",
    midGamePlan: "Hit raider-shadow hunter timing before Human reaches comfortable breaker-caster counts.",
    lateGamePlan: "Stay mobile, isolate human reinforcements, and avoid fighting deep into fortified bases.",
    commonMistakes: [
      "Trading Blademaster health for low-value worker hits",
      "Allowing free level-three Archmage timing",
      "Taking head-on fights into superior Human positioning",
    ],
    heroChoices: ["Blademaster", "Shadow Hunter", "Tauren Chieftain"],
  },
  {
    slug: "human-vs-undead",
    title: "Human vs Undead",
    summary: "Human needs disciplined creeping and a measured expansion plan against Undead's tier-two spikes.",
    difficulty: "High pressure",
    earlyGamePlan: "Protect peasants, deny free fiend creeping, and route militia for safe map progress.",
    midGamePlan: "Pressure statues and hold formation so storm bolt and rifles can punish overextension.",
    lateGamePlan: "Use production depth and healing to outlast smaller Undead armies in longer trades.",
    commonMistakes: [
      "Expanding without scout confirmation",
      "Misusing militia and losing early economy",
      "Taking fights before critical dispel or bolt timing",
    ],
    heroChoices: ["Archmage", "Mountain King", "Paladin"],
  },
  {
    slug: "night-elf-vs-undead",
    title: "Night Elf vs Undead",
    summary: "Night Elf plays for map control and unit preservation while Undead hunts a clean timing attack.",
    difficulty: "Tight margins",
    earlyGamePlan: "Contest fiend creeping and use moonwell-backed skirmishes to limit DK freedom.",
    midGamePlan: "Choose either bears for durability or talons for control before Undead reaches ideal statues and orb.",
    lateGamePlan: "Split push, re-engage on positioning mistakes, and avoid feeding hero levels to nova focus.",
    commonMistakes: [
      "Over-chasing fiends near statues",
      "Taking direct fights without mana advantage",
      "Skipping scouting around destroyer timing",
    ],
    heroChoices: ["Demon Hunter", "Keeper of the Grove", "Naga Sea Witch"],
  },
  {
    slug: "undead-vs-orc",
    title: "Undead vs Orc",
    summary: "Undead must preserve fiends and hero experience long enough to punish Orc's midgame commitment.",
    difficulty: "Execution heavy",
    earlyGamePlan: "Creep safely, deny Blademaster value, and protect your first statue timing.",
    midGamePlan: "Use coil-nova threat to punish raider overextensions and control item-rich map pockets.",
    lateGamePlan: "Scale orb and destroyers only when the game state supports them rather than autopiloting tech.",
    commonMistakes: [
      "Losing fiends during the first scouting skirmish",
      "Taking fights before Lich or orb timing",
      "Underestimating hex around statue positioning",
    ],
    heroChoices: ["Death Knight", "Lich", "Dark Ranger"],
  },
];

export const builds: Build[] = [
  {
    slug: "orc-grunt-raider-shadow-hunter",
    title: "Orc Grunt Raider Shadow Hunter",
    raceName: "Orc",
    raceSlug: "orc",
    summary: "A stable Orc ladder opening built to pressure Human and exploit exposed expansions.",
    difficulty: "Intermediate",
    strategyType: "Tempo Midgame",
    matchupSlug: "orc-vs-human",
    steps: [
      { stepNumber: 1, supply: 6, timing: "0:00", instruction: "Queue peons, altar, burrow, and start scouting for expansion greed." },
      { stepNumber: 2, supply: 18, timing: "1:40", instruction: "Creep efficiently with Blademaster while preserving grunt hit points for the first skirmish." },
      { stepNumber: 3, supply: 28, timing: "3:10", instruction: "Tech to tier two and evaluate whether Human is fast expanding or defending." },
      { stepNumber: 4, supply: 40, timing: "5:15", instruction: "Add Shadow Hunter, bestiary, and secure raider timing for a power spike fight." },
    ],
  },
  {
    slug: "human-rifle-caster-expand",
    title: "Human Rifle Caster Expand",
    raceName: "Human",
    raceSlug: "human",
    summary: "A disciplined Human expansion build that leans on militia efficiency and caster scaling.",
    difficulty: "Intermediate",
    strategyType: "Economic Control",
    matchupSlug: "human-vs-undead",
    steps: [
      { stepNumber: 1, supply: 6, timing: "0:00", instruction: "Open altar and farm, then route peasants for a minimal-loss first creep." },
      { stepNumber: 2, supply: 20, timing: "2:00", instruction: "Commit to expansion timing only if scouting confirms manageable pressure." },
      { stepNumber: 3, supply: 28, timing: "3:40", instruction: "Begin tech and set up blacksmith plus arcane sanctums for stable rifle-caster play." },
      { stepNumber: 4, supply: 42, timing: "6:00", instruction: "Anchor fights around storm bolt and priest sustain rather than chasing deep." },
    ],
  },
  {
    slug: "night-elf-demon-hunter-bears",
    title: "Night Elf Demon Hunter Bears",
    raceName: "Night Elf",
    raceSlug: "night-elf",
    summary: "A resilient Night Elf route that aims for strong sustained fights with bear transitions.",
    difficulty: "Advanced",
    strategyType: "Sustain Timing",
    matchupSlug: "night-elf-vs-undead",
    steps: [
      { stepNumber: 1, supply: 5, timing: "0:00", instruction: "Open with a demon hunter and optimize moonwell usage for early map control." },
      { stepNumber: 2, supply: 20, timing: "2:10", instruction: "Creep safely while contesting the opponent's easiest experience routes." },
      { stepNumber: 3, supply: 30, timing: "4:20", instruction: "Tech quickly, add a second hero, and prepare lore timing into bears." },
      { stepNumber: 4, supply: 46, timing: "7:00", instruction: "Fight only after master training progress supports long engagements." },
    ],
  },
  {
    slug: "undead-dk-lich-fiends",
    title: "Undead DK Lich Fiends",
    raceName: "Undead",
    raceSlug: "undead",
    summary: "A classic Undead timing route that prioritizes fiend count, statue sustain, and burst damage.",
    difficulty: "Intermediate",
    strategyType: "Timing Push",
    matchupSlug: "undead-vs-orc",
    steps: [
      { stepNumber: 1, supply: 5, timing: "0:00", instruction: "Open crypt and altar with a safe acolyte pattern that minimizes early disruption risk." },
      { stepNumber: 2, supply: 20, timing: "2:00", instruction: "Creep efficiently with Death Knight and avoid exposing fiends to unnecessary focus." },
      { stepNumber: 3, supply: 30, timing: "4:00", instruction: "Tech to tier two, add Lich, and finish the first statue before extended fights." },
      { stepNumber: 4, supply: 42, timing: "6:10", instruction: "Use coil-nova and orb timing to force a fight before the opponent is fully stabilized." },
    ],
  },
];

export const favoriteBuilds = builds.slice(0, 3);
